#pragma once

#define CLIENT_COMMON_EVENT														0xA01
#define CLIENT_COMMON_ITEMDROP													0xA02
#define CLIENT_COMMON_JOINGUILDAPPROVE											0xA03
#define CLIENT_COMMON_JOINGUILDREJECT											0xA04
#define CLIENT_COMMON_DISMISSGUILDAPPROVE										0xA05
#define CLIENT_COMMON_DISMISSGUILDREJECT										0xA06
#define CLIENT_COMMON_SETITEM													0xA07
#define CLIENT_COMMON_MAGIC														0xA08
#define CLIENT_COMMON_CLEARGUILDNAME											0xA09
#define CLIENT_COMMON_EVENT_MOTION												0xA10
#define CLIENT_COMMON_COMMAND_LOG												0xA11
#define CLIENT_COMMON_DYNAMICOBJECT												0xA12

// Init
#define CLIENT_REQUEST_INITPLAYER												0xAC11
#define CLIENT_REQUEST_INITDATA													0xAC12

// Commands
#define CLIENT_REQUEST_COMMAND_MOTION											0xAC13
#define CLIENT_REQUEST_COMMAND_COMMON											0xAC14
#define CLIENT_REQUEST_COMMAND_CHECKCONNECTION									0xAC15
#define CLIENT_REQUEST_COMMAND_CHATMSG											0xAC16
#define CLIENT_REQUEST_COMMAND_SHUTUP											0xAC17

// Map 
#define CLIENT_REQUEST_FULLOBJECTDATA											0xAC18
#define CLIENT_REQUEST_PANNING													0xAC19
#define CLIENT_REQUEST_FULLDATACHAR												0xAC20

// Guild
#define CLIENT_REQUEST_CREATENEWGUILD											0xAC21
#define CLIENT_REQUEST_DISBANDGUILD												0xAC22
#define CLIENT_REQUEST_GUILDNAME												0xAC23
#define	CLIENT_REQUEST_BANME													0xAC24

// Crusade Guild
#define CLIENT_REQUEST_SELECTCRUSADEDUTY										0xAC25 
#define CLIENT_REQUEST_MAPSTATUS												0xAC26
#define CLIENT_REQUEST_SETGUILDTELEPORTLOC										0xAC28
#define CLIENT_REQUEST_GUILDTELEPORT											0xAC29
#define CLIENT_REQUEST_SUMMONWARUNIT											0xAC30
#define CLIENT_REQUEST_SETGUILDCONSTRUCTLOC										0xAC31

// Party
#define CLIENT_REQUEST_ACCEPTJOINPARTY											0xAC32
#define CLIENT_REQUEST_JOINPARTY												0xAC33

#define CLIENT_REQUEST_ACTIVATESPECABLTY										0xAC34

// Quest
#define CLIENT_REQUEST_CANCELQUEST												0xAC35
#define CLIENT_REQUEST_QUESTACCEPTED											0xAC36

#define CLIENT_REQUEST_UPGRADEITEM												0xAC37

// CityHall Actions
#define CLIENT_REQUEST_CIVILRIGHT												0xAC38
#define CLIENT_REQUEST_HUNTMODE													0xAC39
#define CLIENT_REQUEST_ITEMSDK													0xAC40


#define CLIENT_REQUEST_CREATESLATE												0xAC41
#define CLIENT_REQUEST_CREATEPOTION												0xAC42
#define CLIENT_REQUEST_BUILDITEM												0xAC43

#define CLIENT_REQUEST_EQUIPITEM												0xAC44
#define CLIENT_REQUEST_RELEASEITEM												0xAC45
#define CLIENT_REQUEST_SETITEMPOS												0xAC46

#define CLIENT_REQUEST_PURCHASEITEM												0xAC47
#define CLIENT_REQUEST_STUDYMAGIC												0xAC48


// Buy - Sell and Repair
#define CLIENT_REQUEST_SELLITEM													0xAC49
#define CLIENT_REQUEST_SELLITEMCONFIRM											0xAC50
#define CLIENT_REQUEST_SELLITEMLIST												0xAC51
#define CLIENT_REQUEST_REPAIRITEM												0xAC52
#define CLIENT_REQUEST_REPAIRITEMCONFIRM										0xAC53
#define CLIENT_REQUEST_REPAIR_ALL												0xAC54

#define CLIENT_RESQUEST_TRADEITEM												0xAC55

#define CLIENT_REQUEST_GIVEITEMTOCHAR											0xAC57

// Exchange
#define CLIENT_REQUEST_EXCHANGEITEMTOCHAR										0xAC58
#define CLIENT_REQUEST_SETEXCHANGEITEM											0xAC59
#define CLIENT_REQUEST_CONFIRMEXCHANGEITEM										0xAC60
#define CLIENT_REQUEST_CANCELEXCHANGEITEM										0xAC61

#define CLIENT_REQUEST_REMOVEITEMEXCHANGE										0xAC62

#define CLIENT_REQUEST_TOGGLECOMBATMODE											0xAC63
#define CLIENT_REQUEST_TOGGLESAFEATTACKMODE										0xAC64

// Gets
#define CLIENT_REQUEST_GETREWARDMONEY											0xAC65
#define CLIENT_REQUEST_GETHEROMANTLE											0xAC67
#define CLIENT_REQUEST_GETFISHTHISTIME											0xAC68
#define CLIENT_REQUEST_GETMAGICABILITY											0xAC69

#define CLIENT_REQUEST_USESKILL													0xAC70
#define CLIENT_REQUEST_SETDOWNSKILLINDEX										0xAC71
#define CLIENT_REQUEST_CRAFTITEM												0xAC72 


#define CLIENT_REQUEST_TALKTONPC												0xAC73

// WH
#define CLIENT_REQUEST_BANKPAGE													0xAC74
#define CLIENT_REQUEST_RETRIEVEITEM												0xAC75

// Teleports
#define CLIENT_REQUEST_TELEPORT													0xAC76
#define CLIENT_REQUEST_TELEPORT_LIST											0xAC77
#define CLIENT_REQUEST_CHARGED_TELEPORT											0xAC78

// Resurrection
#define CLIENT_REQUEST_RESURRECTPLAYER_NO										0xAC79
#define CLIENT_REQUEST_RESURRECTPLAYER_YES										0xAC80

#define CLIENT_REQUEST_USEITEM													0xAC56
#define CLIENT_REQUEST_TOMOEAT													0xAF70

//Assasain
#define CLIENT_REQUEST_GETASSASAINHERO											0xAC81
#define	CLIENT_REQUEST_RESETASSASAIN											0xAC82
#define CLIENT_REQUEST_CHANGEPKEK												0xAC83
#define CLIENT_REQUEST_BUY_ASSAPOINTS											0xAC84 

// Achivements
#define	CLIENT_REQUEST_LISTCOMPLETE												0xAC85

// Market
#define	CLIENT_REQUEST_MARKET_ITEMLIST											0xAC86
#define CLIENT_REQUEST_PURCHASE													0xAC87
#define CLIENT_REQUEST_ITEMTOSELLLIST											0xAC88
#define CLIENT_REQUEST_TIPESELLLIST												0xAC89

// Anti Hack
#define	CLIENT_REQUEST_PROCESSANDDLL											0xAC90

// Others
#define CLIENT_REQUEST_GETOCCUPYFIGHTZONETICKET									0xAC91
#define CLIENT_REQUEST_FIGHTZONE_RESERVE										0xAC92
#define CLIENT_REQUEST_LEVELUPSETTINGS											0xAC93
#define CLIENT_REQUEST_NOTICEMENT												0xAC94
#define CLIENT_REQUEST_RESTART													0xAC95
#define CLIENT_REQUEST_STATECHANGEPOINT											0xAC96
#define CLIENT_REQUEST_ANGEL													0xAC97
#define CLIENT_REQUEST_STATUS_AFK												0xAC98
#define CLIENT_REQUEST_ONLINE_USERS												0xAC99
#define CLIENT_REQUEST_TOPMEMORY												0xAD00
#define CLIENT_REQUEST_MAJESTICS_ITEMS											0xAD01
#define CLIENT_REQUEST_RECALL_COORDS											0xAD02
#define CLIENT_REQUEST_NODISCONNECT												0xAD03
#define	CLIENT_REQUEST_STATUSFRIEND												0xAD04
#define	CLIENT_REQUEST_GUILDMEMBER												0xAD05
//#define CLIENT_REQUEST_LOGOUT													0xAD06
#define	CLIENT_REQUEST_CANCELLOGOUT												0xAD07
//#define CLIENT_REQUEST_PING														0xAD08
//#define	CLIENT_REQUEST_HACKDETECTED												0xAD09
#define	CLIENT_REQUEST_PACKSARPAD												0xAD09
#define CLIENT_REQUEST_DCHACK													0xAD10

#define CLIENT_REQUEST_NOWLOGOUT												0xAD11

// Init
#define CLIENT_RESPONSE_INITPLAYER_OLD											0xDC11
#define CLIENT_RESPONSE_INITPLAYER												0xDC12
#define CLIENT_RESPONSE_INITDATA												0xDC13

// Commands
#define CLIENT_RESPONSE_COMMAND_MOTION											0xDC14

// Party
#define CLIENT_RESPONSE_PARTYCOORDS												0xDC15
#define CLIENT_RESPONSE_PARTYHP													0xDC16
#define CLIENT_RESPONSE_PARTYNAME												0xDC17

// Map
#define CLIENT_RESPONSE_PANNING													0xDC18

// Guild
#define CLIENT_RESPONSE_CREATENEWGUILD											0xDC19
#define CLIENT_RESPONSE_DISBANDGUILD											0xDC20
#define CLIENT_RESPONSE_JOINGUILD												0xDC22
#define CLIENT_RESPONSE_DISMISSGUILD											0xDC23 
#define CLIENT_RESPONSE_GUILDDISBANDED											0xDC24
#define CLIENT_RESPONSE_NEWGUILDSMAN											0xDC25
#define CLIENT_RESPONSE_DISMISSGUILDSMAN										0xDC26
#define CLIENT_RESPONSE_GUILDMEMBER												0xDC27

// Characerts
#define CLIENT_RESPONSE_PLAYERCHARACTERCONTENTS									0xDC28
#define CLIENT_RESPONSE_PLAYERITEMLISTCONTENTS									0xDC29

// CityHall Actions
#define CLIENT_RESPONSE_CIVILRIGHT												0xDC31

#define CLIENT_RESPONSE_RETRIEVEITEM											0xDC32

// Teleports
#define CLIENT_RESPONSE_TELEPORT_LIST											0xDC33
#define CLIENT_RESPONSE_CHARGED_TELEPORT										0xDC34

// Exchange
#define CLIENT_RESPONSE_REMOVEITEMEXCHANGE										0xDC35
#define CLIENT_RESPONSE_WEIGHTEXCHANGE											0xDC36
#define CLIENT_RESPONSE_EXCHANGEITEMCONFIRM										0xDC37

// Market
#define CLIENT_RESPONSE_DELETE_SELL_LIST										0xDC38
#define CLIENT_RESPONSE_ITEMLIST												0xDC39
#define CLIENT_REPONSE_SELLTYPE													0xDC40
#define CLIENT_RESPONSE_MARKET													0xDC41

// Assasain
#define CLIENT_NOTIFY_ASSASAINSPOINTS											0xDC42

// Anti Hack
#define CLIENT_RESPONSE_DELETEHACK												0xDC43
#define CLIENT_RESPONSE_CHECKPROCESS											0xDC44
//#define CLIENT_RESPONSE_PROCESSBLOCKED											0xDC45
#define CLIENT_RESPONSE_PELMASO													0xDC45

// Others
#define CLIENT_RESPONSE_FIGHTZONE_RESERVE										0xDC46
#define CLIENT_RESPONSE_TOTALUSERS												0xDC47
#define CLIENT_RESPONSE_NOTICEMENT												0xDC48
#define CLIENT_RESPONSE_TOPMEMORY_EK											0xDC49
#define CLIENT_REPONSE_PLAYERREP												0xDC50


// Notifications 
#define CLIENT_NOTIFY															0xDC51
#define CLIENT_NOTIFY_ITEMOBTAINED												0xDC52
#define CLIENT_NOTIFY_CANNOTCARRYMOREITEM										0xDC53
#define CLIENT_NOTIFY_ITEMPURCHASED												0xDC54
#define CLIENT_NOTIFY_HP														0xDC55
#define CLIENT_NOTIFY_NOTENOUGHGOLD												0xDC56
#define CLIENT_NOTIFY_KILLED													0xDC57
#define CLIENT_NOTIFY_EXP														0xDC58
#define CLIENT_NOTIFY_MAGICSTUDYSUCCESS											0xDC59
#define CLIENT_NOTIFY_MAGICSTUDYFAIL											0xDC60
#define CLIENT_NOTIFY_SKILLTRAINSUCCESS											0xDC61
#define CLIENT_NOTIFY_MP														0xDC62
#define CLIENT_NOTIFY_SP														0xDC63
#define CLIENT_NOTIFY_LEVELUP													0xDC64
#define CLIENT_NOTIFY_ITEMLIFESPANEND											0xDC65
#define CLIENT_NOTIFY_ITEMTOBANK												0xDC66
#define CLIENT_NOTIFY_PKPENALTY													0xDC67
#define CLIENT_NOTIFY_PKCAPTURED												0xDC68
#define CLIENT_NOTIFY_ENEMYKILLREWARD											0xDC69
#define CLIENT_NOTIFY_GIVEITEMFIN_ERASEITEM										0xDC70
#define CLIENT_NOTIFY_DROPITEMFIN_ERASEITEM										0xDC71
#define CLIENT_NOTIFY_ITEMDEPLETED_ERASEITEM									0xDC72
#define CLIENT_NOTIFY_SKILL														0xDC73
#define CLIENT_NOTIFY_SERVERCHANGE												0xDC74
#define CLIENT_NOTIFY_SETITEMCOUNT												0xDC75
#define CLIENT_NOTIFY_CANNOTITEMTOBANK											0xDC76
#define CLIENT_NOTIFY_MAGICEFFECTON												0xDC77
#define CLIENT_NOTIFY_MAGICEFFECTOFF											0xDC78
#define CLIENT_NOTIFY_SKILLUSINGEND												0xDC79
#define CLIENT_NOTIFY_CANNOTSELLITEM											0xDC80
#define CLIENT_NOTIFY_SELLITEMPRICE												0xDC81
#define CLIENT_NOTIFY_CANNOTREPAIRITEM											0xDC82
#define CLIENT_NOTIFY_REPAIRITEMPRICE											0xDC83
#define CLIENT_NOTIFY_ITEMREPAIRED												0xDC84
#define CLIENT_NOTIFY_ITEMSOLD													0xDC85
#define CLIENT_NOTIFY_PLAYERONGAME												0xDC86
#define CLIENT_NOTIFY_PLAYERNOTONGAME											0xDC87
#define CLIENT_NOTIFY_WHISPERMODEON												0xDC88
#define CLIENT_NOTIFY_WHISPERMODEOFF											0xDC89
#define CLIENT_NOTIFY_PLAYERPROFILE												0xDC90
#define CLIENT_NOTIFY_TRAVELERLIMITEDLEVEL										0xDC91
#define CLIENT_NOTIFY_HUNGER													0xDC92
#define CLIENT_NOTIFY_TOBERECALLED												0xDC93
#define CLIENT_NOTIFY_TIMECHANGE												0xDC94
#define CLIENT_NOTIFY_PLAYERSHUTUP												0xDC95
#define CLIENT_NOTIFY_ADMINUSERLEVELLOW											0xDC96
#define CLIENT_NOTIFY_CANNOTRATING												0xDC97
#define CLIENT_NOTIFY_RATINGPLAYER												0xDC98
#define CLIENT_NOTIFY_NOTICEMSG													0xDC99
#define CLIENT_NOTIFY_EVENTFISHMODE												0xDD00
#define CLIENT_NOTIFY_FISHCHANCE												0xDD01
#define CLIENT_NOTIFY_FISHSUCCESS												0xDD02
#define CLIENT_NOTIFY_FISHFAIL													0xDD03
#define CLIENT_NOTIFY_FISHCANCELED												0xDD04
#define CLIENT_NOTIFY_WHETHERCHANGE												0xDD05
#define CLIENT_NOTIFY_REWARDGOLD												0xDD06
#define CLIENT_NOTIFY_STRINGMSG													0xDD07
#define CLIENT_NOTIFY_SAFEATTACKMODE											0xDD08
#define CLIENT_NOTIFY_SUPERATTACKLEFT											0xDD09
#define CLIENT_NOTIFY_SUPERATTACKLEFT1											0xDD10
#define CLIENT_NOTIFY_SUPERATTACKLEFT2											0xDE11
#define CLIENT_NOTIFY_SUPERATTACKLEFT3											0xDD12
#define CLIENT_NOTIFY_NOMATCHINGPORTION											0xDD13
#define CLIENT_NOTIFY_LOWPORTIONSKILL											0xDD14
#define CLIENT_NOTIFY_PORTIONFAIL												0xDD15
#define CLIENT_NOTIFY_PORTIONSUCCESS											0xDD16
#define CLIENT_NOTIFY_NPCTALK													0xDD17
#define CLIENT_NOTIFY_ADMINIFO													0xDD18
#define CLIENT_NOTIFY_DOWNSKILLINDEXSET											0xDD19
#define CLIENT_NOTIFY_ITEMRELEASED												0xDD20
#define CLIENT_NOTIFY_NOTFLAGSPOT												0xDD21
#define CLIENT_NOTIFY_OPENEXCHANGEWINDOW										0xDD22
#define CLIENT_NOTIFY_SETEXCHANGEITEM											0xDD23
#define CLIENT_NOTIFY_CANCELEXCHANGEITEM										0xDD24
#define CLIENT_NOTIFY_EXCHANGEITEMCOMPLETE										0xDD25
#define CLIENT_NOTIFY_CANNOTGIVEITEM											0xDD26
#define CLIENT_NOTIFY_GIVEITEMFIN_COUNTCHANGED									0xDD27
#define CLIENT_NOTIFY_DROPITEMFIN_COUNTCHANGED									0xDD28
#define CLIENT_NOTIFY_ITEMCOLORCHANGE											0xDD29
#define CLIENT_NOTIFY_QUESTCONTENTS												0xDD30
#define CLIENT_NOTIFY_QUESTABORTED												0xDD31
#define CLIENT_NOTIFY_QUESTCOMPLETED											0xDD32
#define CLIENT_NOTIFY_QUESTREWARD												0xDD33
#define CLIENT_NOTIFY_BUILDITEMSUCCESS											0xDD34
#define CLIENT_NOTIFY_BUILDITEMFAIL												0xDD35
#define CLIENT_NOTIFY_OBSERVERMODE												0xDD36
#define CLIENT_NOTIFY_GLOBALATTACKMODE											0xDD37
#define CLIENT_NOTIFY_DAMAGEMOVE												0xDD38
#define CLIENT_NOTIFY_FORCEDISCONN												0xDD39
#define CLIENT_NOTIFY_FIGHTZONERESERVE											0xDD40
#define CLIENT_NOTIFY_NOGUILDMASTERLEVEL										0xDD41
#define CLIENT_NOTIFY_SUCCESSBANGUILDMAN										0xDD42
#define CLIENT_NOTIFY_CANNOTBANGUILDMAN											0xDD43
#define CLIENT_NOTIFY_QUERY_JOINPARTY											0xDD44
#define CLIENT_NOTIFY_ENERGYSPHERECREATED										0xDD45
#define CLIENT_NOTIFY_ENERGYSPHEREGOALIN										0xDD46
#define CLIENT_NOTIFY_SPECIALABILITYENABLED										0xDD47
#define CLIENT_NOTIFY_SPECIALABILITYSTATUS										0xDD48
#define CLIENT_NOTIFY_CRUSADE													0xDD49
#define CLIENT_NOTIFY_LOCKEDMAP													0xDD50
#define CLIENT_NOTIFY_MAPSTATUSNEXT												0xDD51
#define CLIENT_NOTIFY_MAPSTATUSLAST												0xDD52
#define CLIENT_NOTIFY_METEORSTRIKECOMING										0xDD55
#define CLIENT_NOTIFY_METEORSTRIKEHIT											0xDD56
#define CLIENT_NOTIFY_GRANDMAGICRESULT											0xDD57
#define CLIENT_NOTIFY_NOMORECRUSADESTRUCTURE									0xDD58
#define CLIENT_NOTIFY_CONSTRUCTIONPOINT											0xDD59
#define CLIENT_NOTIFY_TCLOC														0xDD60
#define CLIENT_NOTIFY_CANNOTCONSTRUCT											0xDD61
#define CLIENT_NOTIFY_PARTY														0xDD62
#define CLIENT_NOTIFY_ITEMATTRIBUTECHANGE										0xDD63
#define CLIENT_NOTIFY_GIZONITEMUPGRADELEFT										0xDD64
#define CLIENT_NOTIFY_UPGRADEHEROCAPE											0xDD65
#define CLIENT_NOTIFY_SLATE_CREATESUCCESS										0xDD66
#define CLIENT_NOTIFY_SLATE_CREATEFAIL											0xDD67
#define CLIENT_NOTIFY_GIZONITEMCANGE											0xDD68
#define CLIENT_NOTIFY_REQGUILDNAMEANSWER										0xDD69
#define CLIENT_NOTIFY_RECALLTIMELEFT											0xDD70
#define CLIENT_NOTIFY_ITEMUPGRADEFAIL											0xDD71
#define CLIENT_NOTIFY_NOMOREAGRICULTURE											0xDD73
#define CLIENT_NOTIFY_AGRICULTURESKILLLIMIT										0xDD74
#define CLIENT_NOTIFY_AGRICULTURENOAREA											0xDD75
#define CLIENT_NOTIFY_SETTING_SUCCESS											0xDD76
#define CLIENT_NOTIFY_SETTING_FAILED											0xDD77
#define CLIENT_NOTIFY_STATECHANGE_SUCCESS										0xDD78
#define CLIENT_NOTIFY_STATECHANGE_FAILED										0xDD79
#define CLIENT_NOTIFY_RESURRECTPLAYER											0xDD80
#define CLIENT_NOTIFY_SLATE_INVINCIBLE											0xDD81
#define CLIENT_NOTIFY_SLATE_MANA												0xDD82
#define CLIENT_NOTIFY_SLATE_EXP													0xDD83
#define CLIENT_NOTIFY_SLATE_STATUS												0xDD84
#define CLIENT_NOTIFY_SLATECLEAR												0xDD85
#define CLIENT_NOTIFY_NORECALL													0xDD86
#define CLIENT_NOTIFY_APOCGATEOPEN												0xDD87
#define CLIENT_NOTIFY_APOCGATECLOSE												0xDD88
#define CLIENT_NOTIFY_ABADDONKILLED												0xDD91
#define CLIENT_NOTIFY_MONSTERCOUNT												0xDD92
#define CLIENT_NOTIFY_ANGELIC_STATS												0xDD93 
#define CLIENT_NOTIFY_CRAFTING_SUCCESS											0xDD94 
#define CLIENT_NOTIFY_CRAFTING_FAIL												0xDD95 
#define CLIENT_NOTIFY_QUESTCOUNTER												0xDD96
#define CLIENT_NOTIFY_SPELL_SKILL												0xDD97
#define CLIENT_NOTIFY_ITEMATTRIBUTECHANGEANGEL									0xDD98
#define	CLIENT_NOTIFY_STATUSCHAR												0xDD99
#define CLIENT_NOTIFY_CHARSTATUS												0xDE00
#define CLIENT_NOTIFY_EVENTDATA													0xDE01
#define CLIENT_NOTIFY_LUPOOL													0xDE02
#define CLIENT_NOTIFY_STATUSFRIEND												0xDE03
#define CLIENT_NOTIFY_STATUSFRIEND2												0xDE04
#define CLIENT_NOTIFY_F5DATA													0xDE05
#define	CLIENT_NOTIFY_NOTICEEKMSG												0xDE06
#define CLIENT_NOTIFY_COINS														0xDE07
#define CLIENT_NOTIFY_NOTENOUGHGOLD2											0xDE08
#define	CLIENT_NOTIFY_PINGPLAYERS												0xDE09
#define CLIENT_NOTIFY_CHANGEPLAYMODE											0xDE26

#define CLIENT_NOTIFY_TPFAST													0xDE67			

//Enemy Kills -> Data Reduction
#define CLIENT_NOTIFY_ENEMYKILLS1												0xDE10
#define CLIENT_NOTIFY_ENEMYKILLS2												0xDE12
#define CLIENT_NOTIFY_ENEMYKILLS3												0xDE13

//Contribs -> Data Reduction
#define CLIENT_NOTIFY_CONTRIBUTION1												0xDE14
#define CLIENT_NOTIFY_CONTRIBUTION2												0xDE15
#define CLIENT_NOTIFY_CONTRIBUTION3												0xDE16

#define	CLIENT_NOTIFY_ACHIVEMENTS												0xDE17

// Events
// * Happy Hour
#define CLIENT_NOTIFY_HAPPYHOURSTAR												0xDE18
#define CLIENT_NOTIFY_HAPPYHOUREND												0xDE19

// * HappyDay LaloRamos
#define CLIENT_NOTIFY_HAPPYDAYSTAR												0xDE20
#define CLIENT_NOTIFY_HAPPYDAYEND												0xDE21

// * RushNet
#define CLIENT_NOTIFY_RUSH														0xDE22
#define CLIENT_SEND_HPRELIQUIA													0xDE23
#define CLIENT_NOTIFY_STRUCTURES												0xDE24

// * Capture The Flag
#define CLIENT_NOTIFY_CAPTURETHEFLAG											0xDE27
#define CLIENT_NOTIFY_FLAGCOUNTER												0xDE28

// * Tower Defence
#define CLIENT_NOTIFY_TOWERDEFENCE												0xDE29
#define CLIENT_NOTIFY_TD_STRUCTURES												0xDE30

// * All vs All
#define CLIENT_NOTIFY_INITALLVSALL												0xDE31
#define CLIENT_NOTIFY_ENDALLVSALL												0xDE32
#define CLIENT_NOTIFY_OPENPORTALS												0xDE33

// * Abaddon
#define	CLIENT_NOTIFY_ABADDONMAP												0xDE34
#define	CLIENT_NOTIFY_ABADDONMAPCLOSE											0xDE35

// * City vs City
#define CLIENT_NOTIFY_CVCEND													0xDE36
#define CLIENT_NOTIFY_PRICECLOSE												0xDE37
#define CLIENT_NOTIFY_CVCNOW													0xDE38

// * WorldWar LaloRamos
#define CLIENT_NOTIFY_WWEND														0xDE39
#define CLIENT_NOTIFY_WWNOW														0xDE40

// * Summon-Event
#define CLIENT_NOTIFY_SUMMONEVENT												0xDE41
#define	CLIENT_NOTIFY_NEXTROUND													0xDE42

// * Hell Of Death
#define CLIENT_NOTIFY_HELLOFDEATH												0xDE43
#define CLIENT_NOTIFY_HPSTRUCTURE												0xDE44

// Final Fight
#define CLIENT_NOTIFY_ARENAPVPEVENT_INIT										0xDE45
#define CLIENT_NOTIFY_ARENAPVPEVENT_CLOSE										0xDE46
#define CLIENT_NOTIFY_TOPARENAEVENT												0xDE47
#define	CLIENT_NOTIFY_MYDATAEVENT												0xDE48

// * Extreme LaloRamos
#define CLIENT_NOTIFY_EXTREND														0xDE49
#define CLIENT_NOTIFY_EXTRNOW														0xDE50

// * TowerOfHell LaloRamos
#define CLIENT_NOTIFY_TOHEND														0xDE51
#define CLIENT_NOTIFY_TOHNOW														0xDE52

#define	CLIENT_NOTIFY_FAKE															0xDE53
#define	CLIENT_NOTIFY_CHANGECITY													0xDE54

#define	CLIENT_NOTIFY_QUEST2														0xDE55
#define	CLIENT_NOTIFY_QUEST3														0xDE56

#define	CLIENT_NOTIFY_QUEST2OFF														0xDE57
#define	CLIENT_NOTIFY_QUEST3OFF														0xDE58

#define	CLIENT_NOTIFY_HUNTON														0xDE59
#define	CLIENT_NOTIFY_HUNTOFF														0xDE60

#define	CLIENT_NOTIFY_DKEVENT														0xDE63
#define	CLIENT_NOTIFY_DKEVENTOFF													0xDE64


#define NOT_ITEMDATA																0x0F98D

#define MSGID_REQUEST_CREATENEWACCOUNT												0xDE61
#define MSGID_REQUEST_CHANGEPASSWORD												0x0FC94210

#define NOT_RANKEXP																	0x0F99D
#define NOT_RANKLEVELUP																0x0F97D

#define NOT_OBJECTS_DATA															0x0F70

#define NOT_RANKSTATS																0x0F71
#define NOT_CHANGERANKSTATS															0x0F72

#define NOT_CINSERT																	0x0F73
#define NOT_CDELETE																	0x0F74

#define NOT_SHINNINGSTATUS_ONLYCLIENT												0x0C94D
#define NOT_SHINNINGSTATUS															0x0C95D
#define NOT_OBJECTID																0x0C96D
#define NOT_NPC_HEALTH																0x0C97D
#define NOT_SHINNING_CLEAR															0x0C98D
#define NOT_SHINNING_UPDATE															0x0C99D

// * WorldWar II LaloRamos
#define CLIENT_NOTIFY_WWENDII														0xDE65
#define CLIENT_NOTIFY_WWNOWII														0xDE66

//AllEks
#define CLIENT_NOTIFY_ALLEKSON														0xDE69
#define CLIENT_NOTIFY_ALLEKSOFF														0xDE70

//AllDKEks
#define CLIENT_NOTIFY_ALLDKEKSON														0xDE71
#define CLIENT_NOTIFY_ALLDKEKSOFF														0xDE72

//nucleo


#define DEF_ENTERGAMEMSGTYPE_NEW												0x0F1C

// Login
#define NUCLEO_REQUEST_LOGIN													0xFA98
#define NUCLEO_REQUEST_CREATEACC												0xFA11

//Create/Delete Character
#define NUCLEO_REQUEST_CREATENEWCHARACTER										0xFA12
#define NUCLEO_REQUEST_DELETECHARACTER											0xFA13


#define DEF_LOGRESMSGTYPE_NEWACCOUNTCREATED										0xFA16
#define DEF_LOGRESMSGTYPE_NEWACCOUNTFAILED										0xFA17


// Enter Game
#define NUCLEO_REQUEST_ENTERGAME												0xFA14
#define NUCLEO_REQUEST_NOENTER_FORCEDISCONN										0xFA15

// Login 
#define NUCLEO_RESPONSE_PASSWORDMISMATCH										0xFB01
#define NUCLEO_RESPONSE_NOTEXISTINGACCOUNT										0xFB02

// Create/Delete Character
#define NUCLEO_RESPONSE_NEWCHARACTERCREATED										0xFB03
#define NUCLEO_RESPONSE_NEWCHARACTERFAILED										0xFB04
#define NUCLEO_RESPONSE_ALREADYEXISTINGCHARACTER								0xFB05
#define NUCLEO_RESPONSE_CHARACTERDELETED										0xFB06

// Enter Game
#define NUCLEO_RESPONSE_NOTEXISTINGCHARACTER									0xFB07
#define NUCLEO_RESPONSE_PLAYING													0xFB08
#define NUCLEO_RESPONSE_REJECT													0xFB09
#define NUCLEO_RESPONSE_CONFIRM													0xFB10
#define NUCLEO_RESPONSE_FORCEDISCONN											0xFB11

#define DEF_LOGRESMSGTYPE_PASSWORDCHANGESUCCESS   	    0x0A00		
#define DEF_LOGRESMSGTYPE_PASSWORDCHANGEFAIL			0x0A01


// Register
#define NUCLEO_REQUEST_REGISTERGAMESERVER										0xFB777

// Account
#define NUCLEO_REQUEST_DELETEACCOUNT											0xFB502
#define NUCLEO_REQUEST_SETACCOUNTWAITSTATUS										0xFB503
#define NUCLEO_REQUEST_FORCEDISCONECTACCOUNT									0xFB504

// Characters
#define NUCLEO_REQUEST_PLAYERDATA												0xFB715
#define NUCLEO_ENTERGAMECONFIRM													0xFB874

#define NUCLEO_REQUEST_SAVEPLAYERDATA											0xFB507
#define NUCLEO_REQUEST_SAVEPLAYERDATA_REPLY										0xFB508
#define NUCLEO_REQUEST_SAVEPLAYERDATALOGOUT										0xFB509
#define NUCLEO_REQUEST_NOSAVELOGOUT												0xFB510

// Guilds
#define NUCLEO_REQUEST_CREATENEWGUILD											0xFB511
#define NUCLEO_REQUEST_DISBANDGUILD												0xFB512

#define NUCLEO_REQUEST_NEWGUILDSMAN												0xFB513
#define NUCLEO_REQUEST_DELGUILDSMAN												0xFB514

// Register
#define NUCLEO_RESPONSE_REGISTERGAMESERVER										0xFB874

// Guild
#define NUCLEO_RESPONSE_CREATENEWGUILD											0xFB516
#define NUCLEO_RESPONSE_DISBANDGUILD											0xFB517

// Characters
#define NUCLEO_RESPONSE_PLAYERDATA												0xFB518
#define NUCLEO_RESPONSE_SAVEPLAYERDATA_REPLY									0xFB519


//new messages heaton 2024

#define ENHANCEMENT_EXTRACT 0x1F54
#define ENHANCEMENT_FUSION 0x1F55

#define NOTIFYMSG										    0x0C56
#define NOT_COMMAND									0x0C91D
#define NOTIFY_LEVELCHANGE							0x1F49

#define NOTIFY_EVENT_STATUS 0x0F198
#define NOTIFY_EVENT_STATUS2 0x0F199
#define NOT_DMTOP									0x0C83D
#define NOT_DMPOINTS								0x0C82D
#define CLIENT_NOTIFY_SETTING_STATS					0x0C81D

#define REQUEST_SETMARKETITEM	0x0C52
#define REQUEST_MARKETNAMES	0x0C53
#define REQUEST_MARKETITEMS	0x0C54
#define REQUEST_GETMARKETITEM	0x0C55
#define NOTIFY_ENABLE_ITEM 0x0C02

#define CLIENT_NOTIFY_ITEMREPAIRED2	0x0C57

#define NOT_NEWWEIGHT								0x0C80D
#define NOT_NEWENDURANCE							0x0C79D

#define NOT_CHARQUESTS									0x0C77D
#define NOT_CHARQUESTS2									0x0C76D

#define START_QUEST										0x0C75D
#define DISMISS_QUEST									0x0C74D
#define PAUSE_QUEST										0x0C73D
#define ACTIVE_QUEST									0x0C72D
#define REWARD_QUEST									0x0C71D
#define NOT_QUESTLIST									0x0C70D

#define NOT_TRADE_EK									0x0C69D
#define NOT_TRADE_CONTRIB								0x0C68D
#define NOT_TRADE_COIN									0x0C67D
#define REQ_TRADE										0x0C66D
#define NOT_TRADE_MAJS									0x0C65D
#define REQ_TRADE_BALL									0x0C64D
#define NOT_COMMAND_UDP										0x0C63D
#define NOTIFY_PING											0x0C62D

enum UDPPakets
{
	SOCKMSG_WELCOME,
	SOCKMSG_PING,
	SOCKMSG_COMMAND,
	SOCKMSG_OBJECTCOMMAND,
	SOCKMSG_MSG2,
	SOCKMSG_MSG3,
	SOCKMSG_MSG4,
	SOCKMSG_MSG5
};

enum TradeBalls
{
	BALL_NONE,
	BALL_CONTRIB,
	BALL_COIN,
	BALL_REP,
	BALL_MAJS
};

enum class BItemID : short
{
	ContributionBall = 3052,
	MajesticBall = 3055,
	CoinBall = 3053,
	RepBall = 3054,
};